### PR TITLE
#6 #162966615 A user can post a question 

### PR DESCRIPTION
**Pull request by jackiegitari1234**
**What does this PR do?**
- Creates a page where a user can post a question to a certain meetup

**Description of Task to be completed**
- create a page where a user can post a question to a certain meetup
- display other posted question for the meetup if any
- on the created page include a text area field and a submit button

**How should this be manually tested?**
- clone the repository https://github.com/jackiegitari1234/Questioner on your local machine
- navigate into Questioner/UI by executing the command `cd Questioner/UI`
- open the file `questions.html` using a browser

**What are the relevant pivotal tracker stories?**
https://www.pivotaltracker.com/n/projects/2235314
#162966615

**Screenshot**
qstn

### CODE REVIEW

**Comment by wachiranduati** [comment]
Thats awesome.. :+1:

**Comment by jackiegitari1234** [comment]
Thanks @wachiranduati

**Comment by SolomonMacharia** [comment]
looks great.

**Comment by jackiegitari1234** [comment]
Thanks @wachiranduati and @SolomonMacharia

**Pull request merged**
