### PR TITLE
#163054752 Ft signup 

### PR DESCRIPTION
**Pull request by jackiegitari1234**
**What does this PR do?**
- Creates an end point for a user to sign-up

**Description of Task to be completed?**
- Create an endpoint that enables a user to create an account at Questioner
- all tests created should pass

**How should this be manually tested?**
- clone the repository to your local machine
- run the commands
 -   `source venv/bin/activate`  to create a virtual environment
 -   `export FLASK_ENV=development` to setup the environment 
 - `flask run`
-  use postman to test the end point

What are the relevant pivotal tracker stories?
#163054752

**Screenshots**
sign

### CODE REVIEW

**Comment by SolomonMacharia** [comment]
Good Job

**Comment by jackiegitari1234** [comment]
> Good Job

Thank you

**Comment by wachiranduati** [comment]
Nice work

**Comment by jackiegitari1234** [comment]
> Nice work

thanks

**Pull request merged**
