### PR TITLE
#4 #162966501 Adds a login form

### PR DESCRIPTION
**Pull request by jackiegitari1234**
**What does this PR do?**
- Creates a login form on the home page

**Description of Task to be completed**
- Create a login form
- Ensure labels,buttons and input fields are easily recognizable 

**How should this be manually tested?**
- clone the repository `https://github.com/jackiegitari1234/Questioner` on your local machine
- navigate into Questioner/UI by executing the command `cd Questioner/UI`
- open the file index.html using a browser

**What are the relevant pivotal tracker stories?**
`https://www.pivotaltracker.com/n/projects/2235314`
#162966501

**Screenshot**
login

### CODE REVIEW

**Comment by wachiranduati** [comment]
looks good..

**Comment by SolomonMacharia** [comment]
Nice.

**Comment by jackiegitari1234** [comment]
Thank you @SolomonMacharia and @wachiranduati

**Comment by Sulwe** [comment]
Nice work Jackie, the page is simple and direct to the point

**Comment by exdus** [comment]
awesome

**Comment by jackiegitari1234** [comment]
Thank you @Sulwe  and @exdus

**Pull request merged**
