### PR TITLE
#163008352 creates a profile page 

### PR DESCRIPTION
**Pull request by jackiegitari1234**
**What does this PR do?**
- Creates a UI where a user can view his or her profile

**Description of Task to be completed**
- Create a UI to display user profile
- Add headers for user activities on the Questioner

**How should this be manually tested?**
- clone the repository `https://github.com/jackiegitari1234/Questioner` on your local machine
- navigate into Questioner/UI by executing the command `cd Questioner/UI`
- open the file `profile.html` using a browser

**What are the relevant pivotal tracker stories?**
`https://www.pivotaltracker.com/n/projects/2235314`
#163008352

**Screenshots**
profile

### CODE REVIEW

**Comment by wachiranduati** [comment]
Nice job.

**Comment by colMike** [comment]
It's good...no problems noted.

**Comment by Ogutu-Brian** [comment]
Good job @jackiegitari1234

**Comment by SolomonMacharia** [comment]
Looks nice. Good consistency with the background.

**Pull request merged**
