### PR TITLE
#163284816 modifies the votes endpoint

### PR DESCRIPTION
**Pull request by jackiegitari1234**
**What does this PR do?**
- Modifies the upvote/downvote endpoint

**Description of Task to be completed**
- The endpoint should limit the user to upvoting once
- a user can only downvote once

**How should this be manually tested?**
- clone the repository to your local machine
- run the commands
 -   `source venv/bin/activate`  to create a virtual environment
 -   `export FLASK_ENV=development` to setup the environment 
 - `flask run`
-  use postman to test the end point

What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/n/projects/2235314
#163284816

### CODE REVIEW

**Comment by wangonya** [comment]
The algorithm idea is good. I'd like to see how it works. My two cents: having a for loop inside another for loop is not the best in terms of complexity.

**Comment by betsybeth** [comment]
+1 to @wangonya comment

**Comment by jackiegitari1234** [comment]
> The algorithm idea is good. I'd like to see how it works. My two cents: having a for loop inside another for loop is not the best in terms of complexity.

That's the best I could achieve...maybe explain how I can do away with one loop
One loop is checking if the user has voted, the other one is if the question exists, each loop is executed on different data

**Comment by jackiegitari1234** [comment]
> > The algorithm idea is good. I'd like to see how it works. My two cents: having a for loop inside another for loop is not the best in terms of complexity.
> 
> That's the best I could achieve...maybe explain how I can do away with one loop.
> One loop is checking if the user has voted, the other one checks if the question exists, each loop is executed on different data

In addition to that, am performing two actions, appending the user to a list and increasing the number of votes

**Pull request merged**
